### ISSUE TITLE
peer dependencies

### ISSUE THREAD

**Issue by hanifmazlan** [chrisgriffith/ionic-native-mocks#15]
i install `npm install @ionic-native-mocks/background-geolocation --save` then this warning come out. What to do?

`npm WARN @ionic-native-mocks/background-geolocation@2.0.6 requires a peer of @ionic-native/core@^3.12.0 but none is installed. You must install peer dependencies yourself.`

how to remove this warning?
thanx

**Comment by janpio** [comment]
Warnings for peer deps can mostly be ignored - it is just a warning after all.

What `@ionic-native/core` do you have installed in your project?

**Comment by chrisgriffith** [comment]
I will investigate this shortly (Mac is in the shop).

**Comment by hanifmazlan** [comment]
My `@ionic-native/core` version is `@ionic-native/core: 4.4.0`. Do I need to update it to version 4.5.2 ?
