### ISSUE TITLE
Globalization plugin mock is out of sync with native plugin

### ISSUE THREAD

**Issue by kadza** [chrisgriffith/ionic-native-mocks#22]
GlobalizationOptions interface was introduced: https://github.com/ionic-team/ionic-native/commit/9816ca665011273727de7f77294ad09c71939f30#diff-b3eab06e53f5eb83fcf56e7da89d0879 and the mock needs to be updated accordingly.

**Comment by chrisgriffith** [comment]
Fixed.

**Comment by kadza** [comment]
It works fine. Thanks :)
